extends Node
#Strictly speaking, these should probably be 'accelleration', rather than 'speed', but I am DEEP in the sunk cost rabbithole.
##The acceleration generated by the ship's forward thrusters.
var f_speed = 2
##The acceleration generated by the ship's backward thrusters.
var b_speed = 1
##The acceleration generated by the ship's port and starboard thrusters.
var s_speed = 1
##How quickly the ship can rotate around its own center of mass.
var turn_speed = 0.05
